### ISSUE TITLE
Some questions about BigDAWG

### ISSUE THREAD

**Issue by Wesley8969** [bigdawg-istc/bigdawg#13]
1) According to the query language , the users still need to learn the 3 kinds of query language (postgres , sciDB , Accumulo)  ,it's not easy for users ;The query languages of BigDAWG is just 3 query languages combined together with unique bigdawg query language like bdcast()
2) How could we add more databases? just those three databases are not enough at all

**Comment by mmucklo** [comment]
@Wesley8969 I know this is somewhat delayed, but from someone who's worked on the system:

1) The desire was to expose the richness of each engine's query language, while permitting data locality to shift on a per-query basis to the most efficient engine for the query.

The idea is that one size does not necessarily fit all when it comes to the appropriate engine and language for a query.

For instance, in a traditional system you would have to wrap let's say the Postgres engine with an array-based query language in order to somewhat achive what SciDB offers via it's query language, however you'd suffer the performance drawbacks of running an array query on a RDBMS, something it wasn't built or tuned for.

For example while the data lives permanently in Postgres, the desired end query executes against data _cast_ (or moved temporarily) into SciDB allowing it to execute at SciDB native speed with only the latency of the temporary data migration.

The data migration could still be done to SciDB, and SQL or something like it could be used to query it, but then again, an imperfect translation, or extensions would have to be done to enable one to access the full facility of the SciDB engine over SQL.

2) MySQL and Vertica are supported, as well as querying data over REST APIs.

There are several other stores supported including S-Store and the now defunct Myria.

A few paper citations:
https://cs.brown.edu/research/pubs/theses/masters/2017/tian.yulong.pdf
https://link.springer.com/chapter/10.1007/978-3-030-14177-6_8
https://ieeexplore.ieee.org/document/8091081

If you want to add an additional store, you'll need to consider if you want to add it as an Island (should have a differing data model and query language than those presently provided) or a shim (something that implements an existing data model).

There were some slides on adding an Island that I put together for the talk I did at VLDB. You may want to reach out to the present maintainers for a copy, but barring that I might be able to get you a copy.
